### PR TITLE
Fixed incompatibility with https://github.com/kelektiv/node-cron

### PR DESCRIPTION
**Pull request by cernytomas**
now is possible to create new instance of CronJob with object as first parameter

### CODE REVIEW

**Comment by mazzy89** [comment]
Changes:
- purge unnecessary module `lodash.toarray`
- remove `travis.yml`
- explain in the README why we have this fork
- Update modules and check if they have breaking changes

**Review by mazzy89 — DISMISSED** [review]
Has it been tested properly after updating the dependecies? Other than that it looks good

**Comment by cernytomas** [comment]
Tests have to be fixed

**Review by mazzy89 — CHANGES_REQUESTED** [review]
Review tests

**Comment by cernytomas** [comment]
Tests fixed, thanks for README

**Comment by SomeoneWeird** [comment]
Is there a reason we can't upstream these changes?

**Comment by cernytomas** [comment]
I created an issue and a PR on original. Just don't how long it'll take to owner to merge it

**Pull request merged**
